fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    'psp':
      repo: 'git://github.com/razorsedge/puppet-psp.git'
      ref: '0.0.1'
  symlinks:
    hp: "#{source_dir}"
