name    'ghoneycutt-hp'
version '0.1.1'
source 'git://github.com/ghoneycutt/puppet-module-hp.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage physical nodes manufactured by HP'
description 'Manage physical nodes manufactured by HP'
project_page 'https://github.com/ghoneycutt/puppet-module-hp'

dependency 'puppetlabs/stdlib', '3.2.x'
